package com.kingdee.hrp.sms.common.model;

import com.kingdee.hrp.sms.common.RootModel;

public class FormFieldsKey extends RootModel {
    private Integer classId;

    private String key;

    public Integer getClassId() {
        return classId;
    }

    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table t_form_fields
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        classId("class_id"),
        key("key"),
        page("page"),
        name("name"),
        sqlColumnName("sql_column_name"),
        dataType("data_type"),
        ctrlType("ctrl_type"),
        ctrlIndex("ctrl_index"),
        index("index"),
        display("display"),
        showWidth("show_width"),
        lookUpType("look_up_type"),
        lookUpClassId("look_up_class_id"),
        srcTable("src_table"),
        srcTableAlis("src_table_alis"),
        srcField("src_field"),
        displayField("display_field"),
        displayExt("display_ext"),
        joinType("join_type"),
        filter("filter"),
        defaultValue("default_value"),
        maxValue("max_value"),
        minValue("min_value"),
        mustInput("must_input"),
        needSave("need_save"),
        length("length"),
        lock("lock"),
        isCondition("is_condition"),
        isCount("is_count");

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table t_form_fields
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_form_fields
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_form_fields
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_form_fields
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column) {
            this.column = column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_form_fields
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.column + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table t_form_fields
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.column + " ASC";
        }
    }
}