package com.kingdee.hrp.sms.common.dao.generate;

import com.kingdee.hrp.sms.common.model.AccessControl;
import com.kingdee.hrp.sms.common.model.AccessControlExample;
import com.kingdee.hrp.sms.common.model.AccessControlKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AccessControlMapper {
    long countByExample(AccessControlExample example);

    int deleteByExample(AccessControlExample example);

    int deleteByPrimaryKey(AccessControlKey key);

    int insert(AccessControl record);

    int insertSelective(AccessControl record);

    List<AccessControl> selectByExample(AccessControlExample example);

    AccessControl selectByPrimaryKey(AccessControlKey key);

    int updateByExampleSelective(@Param("record") AccessControl record, @Param("example") AccessControlExample example);

    int updateByExample(@Param("record") AccessControl record, @Param("example") AccessControlExample example);

    int updateByPrimaryKeySelective(AccessControl record);

    int updateByPrimaryKey(AccessControl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_control
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<AccessControl> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_access_control
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<AccessControl> list, @Param("selective") AccessControl.Column ... selective);
}