package com.kingdee.hrp.sms.common.dao.generate;

import com.kingdee.hrp.sms.common.model.CooperationApply;
import com.kingdee.hrp.sms.common.model.CooperationApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CooperationApplyMapper {
    long countByExample(CooperationApplyExample example);

    int deleteByExample(CooperationApplyExample example);

    int deleteByPrimaryKey(Long id);

    int insert(CooperationApply record);

    int insertSelective(CooperationApply record);

    List<CooperationApply> selectByExample(CooperationApplyExample example);

    CooperationApply selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") CooperationApply record, @Param("example") CooperationApplyExample example);

    int updateByExample(@Param("record") CooperationApply record, @Param("example") CooperationApplyExample example);

    int updateByPrimaryKeySelective(CooperationApply record);

    int updateByPrimaryKey(CooperationApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cooperation_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<CooperationApply> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cooperation_apply
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<CooperationApply> list, @Param("selective") CooperationApply.Column ... selective);
}