package com.kingdee.hrp.sms.common.dao.generate;

import com.kingdee.hrp.sms.common.model.HospitalSupplierQualification;
import com.kingdee.hrp.sms.common.model.HospitalSupplierQualificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HospitalSupplierQualificationMapper {
    long countByExample(HospitalSupplierQualificationExample example);

    int deleteByExample(HospitalSupplierQualificationExample example);

    int deleteByPrimaryKey(Long id);

    int insert(HospitalSupplierQualification record);

    int insertSelective(HospitalSupplierQualification record);

    List<HospitalSupplierQualification> selectByExample(HospitalSupplierQualificationExample example);

    HospitalSupplierQualification selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") HospitalSupplierQualification record, @Param("example") HospitalSupplierQualificationExample example);

    int updateByExample(@Param("record") HospitalSupplierQualification record, @Param("example") HospitalSupplierQualificationExample example);

    int updateByPrimaryKeySelective(HospitalSupplierQualification record);

    int updateByPrimaryKey(HospitalSupplierQualification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hospital_supplier_qualification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<HospitalSupplierQualification> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hospital_supplier_qualification
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<HospitalSupplierQualification> list, @Param("selective") HospitalSupplierQualification.Column ... selective);
}