package com.kingdee.hrp.sms.common.dao.generate;

import com.kingdee.hrp.sms.common.model.HospitalSupplier;
import com.kingdee.hrp.sms.common.model.HospitalSupplierExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HospitalSupplierMapper {
    long countByExample(HospitalSupplierExample example);

    int deleteByExample(HospitalSupplierExample example);

    int deleteByPrimaryKey(Long id);

    int insert(HospitalSupplier record);

    int insertSelective(HospitalSupplier record);

    List<HospitalSupplier> selectByExample(HospitalSupplierExample example);

    HospitalSupplier selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") HospitalSupplier record, @Param("example") HospitalSupplierExample example);

    int updateByExample(@Param("record") HospitalSupplier record, @Param("example") HospitalSupplierExample example);

    int updateByPrimaryKeySelective(HospitalSupplier record);

    int updateByPrimaryKey(HospitalSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hospital_supplier
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<HospitalSupplier> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hospital_supplier
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<HospitalSupplier> list, @Param("selective") HospitalSupplier.Column ... selective);
}