package com.kingdee.hrp.sms.common.dao.generate;

import com.kingdee.hrp.sms.common.model.MaterialDocumentType;
import com.kingdee.hrp.sms.common.model.MaterialDocumentTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MaterialDocumentTypeMapper {
    long countByExample(MaterialDocumentTypeExample example);

    int deleteByExample(MaterialDocumentTypeExample example);

    int deleteByPrimaryKey(Long id);

    int insert(MaterialDocumentType record);

    int insertSelective(MaterialDocumentType record);

    List<MaterialDocumentType> selectByExample(MaterialDocumentTypeExample example);

    MaterialDocumentType selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") MaterialDocumentType record, @Param("example") MaterialDocumentTypeExample example);

    int updateByExample(@Param("record") MaterialDocumentType record, @Param("example") MaterialDocumentTypeExample example);

    int updateByPrimaryKeySelective(MaterialDocumentType record);

    int updateByPrimaryKey(MaterialDocumentType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material_document_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<MaterialDocumentType> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_material_document_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<MaterialDocumentType> list, @Param("selective") MaterialDocumentType.Column ... selective);
}