package com.kingdee.hrp.sms.common.dao.generate;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderEntryMapper {
    long countByExample(OrderEntryExample example);

    int deleteByExample(OrderEntryExample example);

    int deleteByPrimaryKey(Long id);

    int insert(OrderEntry record);

    int insertSelective(OrderEntry record);

    List<OrderEntry> selectByExample(OrderEntryExample example);

    OrderEntry selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") OrderEntry record, @Param("example") OrderEntryExample example);

    int updateByExample(@Param("record") OrderEntry record, @Param("example") OrderEntryExample example);

    int updateByPrimaryKeySelective(OrderEntry record);

    int updateByPrimaryKey(OrderEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_entry
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<OrderEntry> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_entry
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<OrderEntry> list, @Param("selective") OrderEntry.Column ... selective);
}