package com.kingdee.hrp.sms.common.dao.generate;

import com.kingdee.hrp.sms.common.model.PurchaseOrderEntry;
import com.kingdee.hrp.sms.common.model.PurchaseOrderEntryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PurchaseOrderEntryMapper {
    long countByExample(PurchaseOrderEntryExample example);

    int deleteByExample(PurchaseOrderEntryExample example);

    int deleteByPrimaryKey(Long id);

    int insert(PurchaseOrderEntry record);

    int insertSelective(PurchaseOrderEntry record);

    List<PurchaseOrderEntry> selectByExample(PurchaseOrderEntryExample example);

    PurchaseOrderEntry selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") PurchaseOrderEntry record, @Param("example") PurchaseOrderEntryExample example);

    int updateByExample(@Param("record") PurchaseOrderEntry record, @Param("example") PurchaseOrderEntryExample example);

    int updateByPrimaryKeySelective(PurchaseOrderEntry record);

    int updateByPrimaryKey(PurchaseOrderEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchase_order_entry
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<PurchaseOrderEntry> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchase_order_entry
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<PurchaseOrderEntry> list, @Param("selective") PurchaseOrderEntry.Column ... selective);
}