package com.kingdee.hrp.sms.common.dao.generate;

import com.kingdee.hrp.sms.common.model.SupplierType;
import com.kingdee.hrp.sms.common.model.SupplierTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SupplierTypeMapper {
    long countByExample(SupplierTypeExample example);

    int deleteByExample(SupplierTypeExample example);

    int deleteByPrimaryKey(Long id);

    int insert(SupplierType record);

    int insertSelective(SupplierType record);

    List<SupplierType> selectByExample(SupplierTypeExample example);

    SupplierType selectByPrimaryKey(Long id);

    int updateByExampleSelective(@Param("record") SupplierType record, @Param("example") SupplierTypeExample example);

    int updateByExample(@Param("record") SupplierType record, @Param("example") SupplierTypeExample example);

    int updateByPrimaryKeySelective(SupplierType record);

    int updateByPrimaryKey(SupplierType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<SupplierType> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier_type
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<SupplierType> list, @Param("selective") SupplierType.Column ... selective);
}