package com.kingdee.hrp.sms.common.dao.generate;

import com.kingdee.hrp.sms.common.model.SystemSetting;
import com.kingdee.hrp.sms.common.model.SystemSettingExample;
import com.kingdee.hrp.sms.common.model.SystemSettingKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SystemSettingMapper {
    long countByExample(SystemSettingExample example);

    int deleteByExample(SystemSettingExample example);

    int deleteByPrimaryKey(SystemSettingKey key);

    int insert(SystemSetting record);

    int insertSelective(SystemSetting record);

    List<SystemSetting> selectByExample(SystemSettingExample example);

    SystemSetting selectByPrimaryKey(SystemSettingKey key);

    int updateByExampleSelective(@Param("record") SystemSetting record, @Param("example") SystemSettingExample example);

    int updateByExample(@Param("record") SystemSetting record, @Param("example") SystemSettingExample example);

    int updateByPrimaryKeySelective(SystemSetting record);

    int updateByPrimaryKey(SystemSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_setting
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<SystemSetting> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_setting
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<SystemSetting> list, @Param("selective") SystemSetting.Column ... selective);
}