package com.kingdee.hrp.sms.common.dao.generate;

import com.kingdee.hrp.sms.common.model.SystemSettings;
import com.kingdee.hrp.sms.common.model.SystemSettingsExample;
import com.kingdee.hrp.sms.common.model.SystemSettingsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemSettingsMapper {
    long countByExample(SystemSettingsExample example);

    int deleteByExample(SystemSettingsExample example);

    int deleteByPrimaryKey(SystemSettingsKey key);

    int insert(SystemSettings record);

    int insertSelective(SystemSettings record);

    List<SystemSettings> selectByExample(SystemSettingsExample example);

    SystemSettings selectByPrimaryKey(SystemSettingsKey key);

    int updateByExampleSelective(@Param("record") SystemSettings record, @Param("example") SystemSettingsExample example);

    int updateByExample(@Param("record") SystemSettings record, @Param("example") SystemSettingsExample example);

    int updateByPrimaryKeySelective(SystemSettings record);

    int updateByPrimaryKey(SystemSettings record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_settings
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<SystemSettings> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_system_settings
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<SystemSettings> list, @Param("selective") SystemSettings.Column ... selective);
}