$axure.loadCurrentPage({
  "url":"orders-handle.html",
  "generationDate":new Date(1422865171541.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"window"],
  "page":{
    "packageId":"d5014f383ecb47f7893520740681de37",
    "type":"Axure:Page",
    "name":"orders-handle",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"322677e02b9648ed9a376b93b519abf0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1062,
              "height":1268}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e31247f651724bc3b86263c1a52af9cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1062,
                  "height":1268}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-handle/u0.png"}},
{
          "id":"cad0e3cf228246babe7fcc9b33b96eba",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1278},
            "size":{
              "width":415,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1ae87f377a94281a86d3ab0c230045c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "size":{
                  "width":208,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5f0b991b9e6d4477bc4772f3e77bf6d8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "size":{
                      "width":208,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/send-goods/u352.png"}},
{
              "id":"306b490d85954be5aad22ec08dc63880",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":33},
                "size":{
                  "width":208,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9fd0a4211c2a49d58f6487d0065f840a",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":33},
                    "size":{
                      "width":208,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/print/u275.png"}},
{
              "id":"ba806d3239fd460db31e92616e72b41a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":208,
                  "y":0},
                "size":{
                  "width":207,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a378506ce1724857ae250cc8d53e415e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":208,
                      "y":0},
                    "size":{
                      "width":207,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/send-goods/u354.png"}},
{
              "id":"cb66825e72f64a318f436f5ab77c312d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":208,
                  "y":33},
                "size":{
                  "width":207,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"fb17dc6ec2044fe08562049e30f2bfbe",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":208,
                      "y":33},
                    "size":{
                      "width":207,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/print/u277.png"}}]},
{
          "id":"775789467c00469283d96afa51c1ef6c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1351},
            "size":{
              "width":935,
              "height":1006}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9cd078f4ac3e4ea4a889bff0106a9bcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1351},
                "size":{
                  "width":935,
                  "height":1006}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-handle/u11.png"}},
{
          "id":"89f8be320da742e8a695975ab1ea0c30",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":2386},
            "size":{
              "width":415,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"991f8e84c72b4182b85825658df09058",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "size":{
                  "width":208,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"acdf96ed435f4a1ba5712bf504133ae9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "size":{
                      "width":208,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/send-goods/u352.png"}},
{
              "id":"a5414731191d4b2f98ccc8f602badf2c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":33},
                "size":{
                  "width":208,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"12a15f900ffb43e18bbf2ae9ff4e593d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":33},
                    "size":{
                      "width":208,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/print/u275.png"}},
{
              "id":"6d2f941425364da093c678ae56d79220",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":208,
                  "y":0},
                "size":{
                  "width":207,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9aade17152774a8f829e1ed722b396bd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":208,
                      "y":0},
                    "size":{
                      "width":207,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/send-goods/u354.png"}},
{
              "id":"a4a387a70dc9447287fa199a316f7d55",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":208,
                  "y":33},
                "size":{
                  "width":207,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f2a58df2599840dea5f04dd650bf096c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":208,
                      "y":33},
                    "size":{
                      "width":207,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/print/u277.png"}}]},
{
          "id":"3e7542692cee4475acbcff5e9a79ceb5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":2459},
            "size":{
              "width":949,
              "height":995}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ae1f4913ff94b94aa8329c5d10b9b40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":2459},
                "size":{
                  "width":949,
                  "height":995}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-handle/u22.png"}},
{
          "id":"2b95b87e271f4f1aad287411ec5a17a9",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":3500},
            "size":{
              "width":415,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0e54d5f01ce4d769bb179a27fb99744",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "size":{
                  "width":208,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c2ecbd2de0474510bd28c8ab1021b511",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "size":{
                      "width":208,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/send-goods/u352.png"}},
{
              "id":"4289db5763b1452abf18f2042daedebf",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":33},
                "size":{
                  "width":208,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2c19da11761b4b50a9ad392fd22df770",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":33},
                    "size":{
                      "width":208,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/print/u275.png"}},
{
              "id":"bf5b7dd376f049e88ffce68176da3f89",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":208,
                  "y":0},
                "size":{
                  "width":207,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5855c437c1844355912b6a0b0ed6e7c1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":208,
                      "y":0},
                    "size":{
                      "width":207,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/send-goods/u354.png"}},
{
              "id":"5579f208ee9f4f6c8b00705fc6ddfdba",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":208,
                  "y":33},
                "size":{
                  "width":207,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9ede8a451b2542bf9b8b76c5012fd897",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":208,
                      "y":33},
                    "size":{
                      "width":207,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/print/u277.png"}}]},
{
          "id":"7afc59ac45994d1783bf6ca94621d135",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":3605},
            "size":{
              "width":654,
              "height":585}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"731d579c6c9d4cffb44905feb8f48abd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":3605},
                "size":{
                  "width":654,
                  "height":585}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-handle/u33.png"}},
{
          "id":"25f4aee94ff346dcb1b400933a34fff7",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":4217},
            "size":{
              "width":415,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e8b89a56b814acd9495a8b5ee3cae99",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "size":{
                  "width":208,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6ae84e8fc5594e2da062a6a130c04e7e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "size":{
                      "width":208,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/send-goods/u352.png"}},
{
              "id":"183557182b9a4f459a8b92b75386e8cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":33},
                "size":{
                  "width":208,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"314be403cdfd46428b87e1e90ec05d78",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":33},
                    "size":{
                      "width":208,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/print/u275.png"}},
{
              "id":"31a6719381af4b09bf784052c8b02d73",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":208,
                  "y":0},
                "size":{
                  "width":207,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a39caac1eebb4962ba7d37cd5bb2d927",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":208,
                      "y":0},
                    "size":{
                      "width":207,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/send-goods/u354.png"}},
{
              "id":"fde293949c7a4f34936e37dfda1d8bad",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":208,
                  "y":33},
                "size":{
                  "width":207,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"aee9839dac72432794529af652a88522",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":208,
                      "y":33},
                    "size":{
                      "width":207,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/print/u277.png"}}]},
{
          "id":"a06c62429b4a4945988cecbf20fd1136",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":4310},
            "size":{
              "width":935,
              "height":1006}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2187669647784fb79e3c3da2004604a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":4310},
                "size":{
                  "width":935,
                  "height":1006}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-handle/u44.png"}},
{
          "id":"cbdae2aaa3314d519722047c8f24434a",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":5340},
            "size":{
              "width":415,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb4dad2fa64a449f967886d346ee5327",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "size":{
                  "width":208,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9998a6355bd54fea9746024ae27a2b65",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "size":{
                      "width":208,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/send-goods/u352.png"}},
{
              "id":"ab1d5db529084a7fadd0f56c2d24bdd4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":33},
                "size":{
                  "width":208,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a6d8f0b9c8374becb71788438ac27988",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":33},
                    "size":{
                      "width":208,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/print/u275.png"}},
{
              "id":"b48ce90980f243e39d818b1076cd259d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":208,
                  "y":0},
                "size":{
                  "width":207,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"7e37fa90e2c242e7879df4a2082149a4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":208,
                      "y":0},
                    "size":{
                      "width":207,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/send-goods/u354.png"}},
{
              "id":"c808e93fccf2456d8b31f59cf881d999",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":208,
                  "y":33},
                "size":{
                  "width":207,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2ebc8531d70d4ea5813a3905b0bf2911",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":208,
                      "y":33},
                    "size":{
                      "width":207,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/print/u277.png"}}]},
{
          "id":"965ac9ef8d9a443dafd5cc073c016bca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-14,
              "y":5440},
            "size":{
              "width":924,
              "height":780}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"52371aef5cb24331957a8d9a93103824",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-14,
                  "y":5440},
                "size":{
                  "width":924,
                  "height":780}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-handle/u55.png"}},
{
          "id":"56b1345e85694bfbbf37a4e39e21bb6d",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":6200},
            "size":{
              "width":415,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be24b46156874d848c3f09de4bfc0a42",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "size":{
                  "width":208,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c5e8e6af78814c829e10e8e6c7c8eab1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "size":{
                      "width":208,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/send-goods/u352.png"}},
{
              "id":"26f95a9947b74e9283e1c13cc87780ad",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":33},
                "size":{
                  "width":208,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"592ce3ea0e564f6db3f42d6d40edf7bf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":33},
                    "size":{
                      "width":208,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/print/u275.png"}},
{
              "id":"d408b8e51fe145dcb1b1e2507f68eab7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":208,
                  "y":0},
                "size":{
                  "width":207,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"786997f9956f45aeb6e23f66fcdfe475",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":208,
                      "y":0},
                    "size":{
                      "width":207,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/send-goods/u354.png"}},
{
              "id":"2a4ec2845cf84a86bc0ced63b5d7d8da",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":208,
                  "y":33},
                "size":{
                  "width":207,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a85255e62e4c463caf6d0082fa17480e",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":208,
                      "y":33},
                    "size":{
                      "width":207,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/print/u277.png"}}]},
{
          "id":"b012209783c14c858eae7ee93c59c886",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":6310},
            "size":{
              "width":873,
              "height":993}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7b8c623d5fb4e44afcdd78e4e6295c2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":6310},
                "size":{
                  "width":873,
                  "height":993}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-handle/u66.png"}},
{
          "id":"c1f17815f7fc4a749d991f31cdc1b33b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":7252},
            "size":{
              "width":924,
              "height":1788}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88bc0aeec3d849228264a606c0fc67ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":7252},
                "size":{
                  "width":924,
                  "height":1788}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-handle/u68.png"}},
{
          "id":"4e8200877ce6427193d89a393fb7f225",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":9080},
            "size":{
              "width":415,
              "height":63}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"886a96f78d314ccaab320742d98d4d6b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "size":{
                  "width":208,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"abc0505327cd42649024a567e5c81e48",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "size":{
                      "width":208,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/send-goods/u352.png"}},
{
              "id":"1823519d74c24c928f39e19a486037f4",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":33},
                "size":{
                  "width":208,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"3f8102d554bf49649e3f5aad56dc418b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":33},
                    "size":{
                      "width":208,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/print/u275.png"}},
{
              "id":"95099a1db41d4079b27a6deee4f132b5",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":208,
                  "y":0},
                "size":{
                  "width":207,
                  "height":33}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"358b810bc66e487eaa464da86ed60b4c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF009DD9},
                    "location":{
                      "x":208,
                      "y":0},
                    "size":{
                      "width":207,
                      "height":33}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/send-goods/u354.png"}},
{
              "id":"2ae19e01d4bf42b4aec6b25d90739561",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":208,
                  "y":33},
                "size":{
                  "width":207,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"f046290fbd994fe0b58f36b86696db06",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":208,
                      "y":33},
                    "size":{
                      "width":207,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/print/u277.png"}}]},
{
          "id":"e2984bb470e14181aa815a249c400e0a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":9160},
            "size":{
              "width":939,
              "height":605}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e18298593c64cb1a5923860bae6a1cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":9160},
                "size":{
                  "width":939,
                  "height":605}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/orders-handle/u79.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "322677e02b9648ed9a376b93b519abf0":{
      "scriptId":"u0"},
    "e31247f651724bc3b86263c1a52af9cf":{
      "scriptId":"u1"},
    "cad0e3cf228246babe7fcc9b33b96eba":{
      "scriptId":"u2"},
    "b1ae87f377a94281a86d3ab0c230045c":{
      "scriptId":"u3"},
    "5f0b991b9e6d4477bc4772f3e77bf6d8":{
      "scriptId":"u4"},
    "ba806d3239fd460db31e92616e72b41a":{
      "scriptId":"u5"},
    "a378506ce1724857ae250cc8d53e415e":{
      "scriptId":"u6"},
    "306b490d85954be5aad22ec08dc63880":{
      "scriptId":"u7"},
    "9fd0a4211c2a49d58f6487d0065f840a":{
      "scriptId":"u8"},
    "cb66825e72f64a318f436f5ab77c312d":{
      "scriptId":"u9"},
    "fb17dc6ec2044fe08562049e30f2bfbe":{
      "scriptId":"u10"},
    "775789467c00469283d96afa51c1ef6c":{
      "scriptId":"u11"},
    "9cd078f4ac3e4ea4a889bff0106a9bcb":{
      "scriptId":"u12"},
    "89f8be320da742e8a695975ab1ea0c30":{
      "scriptId":"u13"},
    "991f8e84c72b4182b85825658df09058":{
      "scriptId":"u14"},
    "acdf96ed435f4a1ba5712bf504133ae9":{
      "scriptId":"u15"},
    "6d2f941425364da093c678ae56d79220":{
      "scriptId":"u16"},
    "9aade17152774a8f829e1ed722b396bd":{
      "scriptId":"u17"},
    "a5414731191d4b2f98ccc8f602badf2c":{
      "scriptId":"u18"},
    "12a15f900ffb43e18bbf2ae9ff4e593d":{
      "scriptId":"u19"},
    "a4a387a70dc9447287fa199a316f7d55":{
      "scriptId":"u20"},
    "f2a58df2599840dea5f04dd650bf096c":{
      "scriptId":"u21"},
    "3e7542692cee4475acbcff5e9a79ceb5":{
      "scriptId":"u22"},
    "1ae1f4913ff94b94aa8329c5d10b9b40":{
      "scriptId":"u23"},
    "2b95b87e271f4f1aad287411ec5a17a9":{
      "scriptId":"u24"},
    "c0e54d5f01ce4d769bb179a27fb99744":{
      "scriptId":"u25"},
    "c2ecbd2de0474510bd28c8ab1021b511":{
      "scriptId":"u26"},
    "bf5b7dd376f049e88ffce68176da3f89":{
      "scriptId":"u27"},
    "5855c437c1844355912b6a0b0ed6e7c1":{
      "scriptId":"u28"},
    "4289db5763b1452abf18f2042daedebf":{
      "scriptId":"u29"},
    "2c19da11761b4b50a9ad392fd22df770":{
      "scriptId":"u30"},
    "5579f208ee9f4f6c8b00705fc6ddfdba":{
      "scriptId":"u31"},
    "9ede8a451b2542bf9b8b76c5012fd897":{
      "scriptId":"u32"},
    "7afc59ac45994d1783bf6ca94621d135":{
      "scriptId":"u33"},
    "731d579c6c9d4cffb44905feb8f48abd":{
      "scriptId":"u34"},
    "25f4aee94ff346dcb1b400933a34fff7":{
      "scriptId":"u35"},
    "8e8b89a56b814acd9495a8b5ee3cae99":{
      "scriptId":"u36"},
    "6ae84e8fc5594e2da062a6a130c04e7e":{
      "scriptId":"u37"},
    "31a6719381af4b09bf784052c8b02d73":{
      "scriptId":"u38"},
    "a39caac1eebb4962ba7d37cd5bb2d927":{
      "scriptId":"u39"},
    "183557182b9a4f459a8b92b75386e8cc":{
      "scriptId":"u40"},
    "314be403cdfd46428b87e1e90ec05d78":{
      "scriptId":"u41"},
    "fde293949c7a4f34936e37dfda1d8bad":{
      "scriptId":"u42"},
    "aee9839dac72432794529af652a88522":{
      "scriptId":"u43"},
    "a06c62429b4a4945988cecbf20fd1136":{
      "scriptId":"u44"},
    "2187669647784fb79e3c3da2004604a1":{
      "scriptId":"u45"},
    "cbdae2aaa3314d519722047c8f24434a":{
      "scriptId":"u46"},
    "fb4dad2fa64a449f967886d346ee5327":{
      "scriptId":"u47"},
    "9998a6355bd54fea9746024ae27a2b65":{
      "scriptId":"u48"},
    "b48ce90980f243e39d818b1076cd259d":{
      "scriptId":"u49"},
    "7e37fa90e2c242e7879df4a2082149a4":{
      "scriptId":"u50"},
    "ab1d5db529084a7fadd0f56c2d24bdd4":{
      "scriptId":"u51"},
    "a6d8f0b9c8374becb71788438ac27988":{
      "scriptId":"u52"},
    "c808e93fccf2456d8b31f59cf881d999":{
      "scriptId":"u53"},
    "2ebc8531d70d4ea5813a3905b0bf2911":{
      "scriptId":"u54"},
    "965ac9ef8d9a443dafd5cc073c016bca":{
      "scriptId":"u55"},
    "52371aef5cb24331957a8d9a93103824":{
      "scriptId":"u56"},
    "56b1345e85694bfbbf37a4e39e21bb6d":{
      "scriptId":"u57"},
    "be24b46156874d848c3f09de4bfc0a42":{
      "scriptId":"u58"},
    "c5e8e6af78814c829e10e8e6c7c8eab1":{
      "scriptId":"u59"},
    "d408b8e51fe145dcb1b1e2507f68eab7":{
      "scriptId":"u60"},
    "786997f9956f45aeb6e23f66fcdfe475":{
      "scriptId":"u61"},
    "26f95a9947b74e9283e1c13cc87780ad":{
      "scriptId":"u62"},
    "592ce3ea0e564f6db3f42d6d40edf7bf":{
      "scriptId":"u63"},
    "2a4ec2845cf84a86bc0ced63b5d7d8da":{
      "scriptId":"u64"},
    "a85255e62e4c463caf6d0082fa17480e":{
      "scriptId":"u65"},
    "b012209783c14c858eae7ee93c59c886":{
      "scriptId":"u66"},
    "a7b8c623d5fb4e44afcdd78e4e6295c2":{
      "scriptId":"u67"},
    "c1f17815f7fc4a749d991f31cdc1b33b":{
      "scriptId":"u68"},
    "88bc0aeec3d849228264a606c0fc67ba":{
      "scriptId":"u69"},
    "4e8200877ce6427193d89a393fb7f225":{
      "scriptId":"u70"},
    "886a96f78d314ccaab320742d98d4d6b":{
      "scriptId":"u71"},
    "abc0505327cd42649024a567e5c81e48":{
      "scriptId":"u72"},
    "95099a1db41d4079b27a6deee4f132b5":{
      "scriptId":"u73"},
    "358b810bc66e487eaa464da86ed60b4c":{
      "scriptId":"u74"},
    "1823519d74c24c928f39e19a486037f4":{
      "scriptId":"u75"},
    "3f8102d554bf49649e3f5aad56dc418b":{
      "scriptId":"u76"},
    "2ae19e01d4bf42b4aec6b25d90739561":{
      "scriptId":"u77"},
    "f046290fbd994fe0b58f36b86696db06":{
      "scriptId":"u78"},
    "e2984bb470e14181aa815a249c400e0a":{
      "scriptId":"u79"},
    "4e18298593c64cb1a5923860bae6a1cb":{
      "scriptId":"u80"}}});