$axure.loadCurrentPage({
  "url":"order-info.html",
  "generationDate":new Date(1422865172133.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"window"],
  "page":{
    "packageId":"37a6383555a4495788547e78c139aeb1",
    "type":"Axure:Page",
    "name":"order-info",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9dee168be35f443eba4e7169d0920498",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1008,
              "height":1369}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce0502e2775b400e8fbd6d27cd39877e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1008,
                  "height":1369}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/order-info/u0.png"}},
{
          "id":"8ba57b2d9db14aebbb393edc0bd99370",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":1369},
            "size":{
              "width":1001,
              "height":1368}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14e7db08b1fd44e0abfdc3aff8329a61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":1369},
                "size":{
                  "width":1001,
                  "height":1368}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/order-info/u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9dee168be35f443eba4e7169d0920498":{
      "scriptId":"u0"},
    "ce0502e2775b400e8fbd6d27cd39877e":{
      "scriptId":"u1"},
    "8ba57b2d9db14aebbb393edc0bd99370":{
      "scriptId":"u2"},
    "14e7db08b1fd44e0abfdc3aff8329a61":{
      "scriptId":"u3"}}});