$axure.loadCurrentPage({
  "url":"print-setting.html",
  "generationDate":new Date(1422865169269.74),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"window"],
  "page":{
    "packageId":"c6005624e53e458abb5ff118031c0980",
    "type":"Axure:Page",
    "name":"print-setting",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f70b43c2a4fc42d7988c3890b2249a3a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":129},
            "size":{
              "width":1109,
              "height":702},
            "limbo":true,
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f4bac243cb2407e8bc0a985b697a1e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":129},
                "size":{
                  "width":1109,
                  "height":702},
                "limbo":true,
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/print-setting/u0.png"}},
{
          "id":"ec5daefe02c846659562a2d4132d34b4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":540},
            "size":{
              "width":108,
              "height":103},
            "limbo":true},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07e129b68a2443b88fda53fc084fb7b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":418,
                  "y":540},
                "size":{
                  "width":108,
                  "height":103},
                "limbo":true},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/print-setting/u2.png"}},
{
          "id":"9ad38e270851418c942cc1063de232a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":67},
            "size":{
              "width":32,
              "height":34},
            "limbo":true},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"893e713dc23c4c54ba08080a785c2b5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":67},
                "size":{
                  "width":32,
                  "height":34},
                "limbo":true},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"efe0c3749a1049b98068480f2a57467c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":139},
            "size":{
              "width":1109,
              "height":702},
            "limbo":true,
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1646fc8185c4e4eb1089c4c49d9cf5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":46,
                  "y":139},
                "size":{
                  "width":1109,
                  "height":702},
                "limbo":true,
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/print-setting/u0.png"}},
{
          "id":"490652e3a43e4d1eb2dd61a76f3beac3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":550},
            "size":{
              "width":108,
              "height":103},
            "limbo":true},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d92ff05c14b4c24807c9e9debec6ded",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":428,
                  "y":550},
                "size":{
                  "width":108,
                  "height":103},
                "limbo":true},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/print-setting/u2.png"}},
{
          "id":"8bbc3e8b909b4f239136e885ce945a53",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":228,
              "y":77},
            "size":{
              "width":32,
              "height":34},
            "limbo":true},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a074cf61d964350a465312106a5c9e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":228,
                  "y":77},
                "size":{
                  "width":32,
                  "height":34},
                "limbo":true},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"329152fceba04fc7ad176bbfaeaee415",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":129},
            "size":{
              "width":1109,
              "height":702},
            "limbo":true,
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34a37b459dc342bf90651ca872220391",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":129},
                "size":{
                  "width":1109,
                  "height":702},
                "limbo":true,
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/print-setting/u0.png"}},
{
          "id":"4cca7dcf868440b9af95237adfb8c623",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":540},
            "size":{
              "width":108,
              "height":103},
            "limbo":true},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8ad29d51861413fa8b449747184c12e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":418,
                  "y":540},
                "size":{
                  "width":108,
                  "height":103},
                "limbo":true},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/print-setting/u2.png"}},
{
          "id":"2261fad352794ed8ad53a675ed06dee0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":67},
            "size":{
              "width":32,
              "height":34},
            "limbo":true},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c3f2c862edd4c70b630622aeca2818d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":67},
                "size":{
                  "width":32,
                  "height":34},
                "limbo":true},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a33357cdaf58418f996f4c05e1b8fb63",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":185},
            "size":{
              "width":1109,
              "height":702},
            "limbo":true,
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8778cb1ffae64493971be7fc80607577",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":185},
                "size":{
                  "width":1109,
                  "height":702},
                "limbo":true,
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/print-setting/u0.png"}},
{
          "id":"f9138668f161460487db66bf3d96d9d1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":562,
              "y":596},
            "size":{
              "width":108,
              "height":103},
            "limbo":true},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a5acc5a49904f1ebe662b61d1a0c1d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":562,
                  "y":596},
                "size":{
                  "width":108,
                  "height":103},
                "limbo":true},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/print-setting/u2.png"}},
{
          "id":"38ca9ae1689d4159846a303837a20658",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":362,
              "y":123},
            "size":{
              "width":32,
              "height":34},
            "limbo":true},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74d282d2dd9a4aeaacb6e95cdb5d41f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":362,
                  "y":123},
                "size":{
                  "width":32,
                  "height":34},
                "limbo":true},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a845fc87f6ae4eb895306785b5874a48",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":129},
            "size":{
              "width":1109,
              "height":702},
            "limbo":true,
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7decada9bb6c45fe9673beb2131b590e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":129},
                "size":{
                  "width":1109,
                  "height":702},
                "limbo":true,
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/print-setting/u0.png"}},
{
          "id":"e88562250f97443db331cf3c68a74106",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":418,
              "y":540},
            "size":{
              "width":108,
              "height":103},
            "limbo":true},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df228b5fa02641019d301bca5d337283",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":418,
                  "y":540},
                "size":{
                  "width":108,
                  "height":103},
                "limbo":true},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/print-setting/u2.png"}},
{
          "id":"12d78a6c6d6f48f7b56d1caf714e47f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":67},
            "size":{
              "width":32,
              "height":34},
            "limbo":true},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31f2ae11d2c14f48bf09cdea105150df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":67},
                "size":{
                  "width":32,
                  "height":34},
                "limbo":true},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6312dc764d27423cb7bd9c88d1780d8f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1109,
              "height":702}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8840bc360d624a68a25e74a43105d2fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1109,
                  "height":702}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/print-setting/u30.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f70b43c2a4fc42d7988c3890b2249a3a":{
      "scriptId":"u0"},
    "0f4bac243cb2407e8bc0a985b697a1e7":{
      "scriptId":"u1"},
    "ec5daefe02c846659562a2d4132d34b4":{
      "scriptId":"u2"},
    "07e129b68a2443b88fda53fc084fb7b5":{
      "scriptId":"u3"},
    "9ad38e270851418c942cc1063de232a1":{
      "scriptId":"u4"},
    "893e713dc23c4c54ba08080a785c2b5b":{
      "scriptId":"u5"},
    "efe0c3749a1049b98068480f2a57467c":{
      "scriptId":"u6"},
    "c1646fc8185c4e4eb1089c4c49d9cf5b":{
      "scriptId":"u7"},
    "490652e3a43e4d1eb2dd61a76f3beac3":{
      "scriptId":"u8"},
    "0d92ff05c14b4c24807c9e9debec6ded":{
      "scriptId":"u9"},
    "8bbc3e8b909b4f239136e885ce945a53":{
      "scriptId":"u10"},
    "9a074cf61d964350a465312106a5c9e3":{
      "scriptId":"u11"},
    "329152fceba04fc7ad176bbfaeaee415":{
      "scriptId":"u12"},
    "34a37b459dc342bf90651ca872220391":{
      "scriptId":"u13"},
    "4cca7dcf868440b9af95237adfb8c623":{
      "scriptId":"u14"},
    "a8ad29d51861413fa8b449747184c12e":{
      "scriptId":"u15"},
    "2261fad352794ed8ad53a675ed06dee0":{
      "scriptId":"u16"},
    "9c3f2c862edd4c70b630622aeca2818d":{
      "scriptId":"u17"},
    "a33357cdaf58418f996f4c05e1b8fb63":{
      "scriptId":"u18"},
    "8778cb1ffae64493971be7fc80607577":{
      "scriptId":"u19"},
    "f9138668f161460487db66bf3d96d9d1":{
      "scriptId":"u20"},
    "6a5acc5a49904f1ebe662b61d1a0c1d8":{
      "scriptId":"u21"},
    "38ca9ae1689d4159846a303837a20658":{
      "scriptId":"u22"},
    "74d282d2dd9a4aeaacb6e95cdb5d41f3":{
      "scriptId":"u23"},
    "a845fc87f6ae4eb895306785b5874a48":{
      "scriptId":"u24"},
    "7decada9bb6c45fe9673beb2131b590e":{
      "scriptId":"u25"},
    "e88562250f97443db331cf3c68a74106":{
      "scriptId":"u26"},
    "df228b5fa02641019d301bca5d337283":{
      "scriptId":"u27"},
    "12d78a6c6d6f48f7b56d1caf714e47f8":{
      "scriptId":"u28"},
    "31f2ae11d2c14f48bf09cdea105150df":{
      "scriptId":"u29"},
    "6312dc764d27423cb7bd9c88d1780d8f":{
      "scriptId":"u30"},
    "8840bc360d624a68a25e74a43105d2fd":{
      "scriptId":"u31"}}});