$axure.loadCurrentPage({
  "url":"warehouse-setting.html",
  "generationDate":new Date(1422865166301.14),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"window"],
  "page":{
    "packageId":"6889a1b4c94f4ae2acb8f20bb6c10b41",
    "type":"Axure:Page",
    "name":"warehouse-setting",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f79797497f084814a14fc8e8a88a45d1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1115,
              "height":671}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc181d58dcc14230a214c7cf7f80e4f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1115,
                  "height":671}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/warehouse-setting/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f79797497f084814a14fc8e8a88a45d1":{
      "scriptId":"u0"},
    "cc181d58dcc14230a214c7cf7f80e4f3":{
      "scriptId":"u1"}}});