$axure.loadCurrentPage({
  "url":"task.html",
  "generationDate":new Date(1422865171926.27),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"window"],
  "page":{
    "packageId":"147d3e33f2924ebcaa85d024d727df71",
    "type":"Axure:Page",
    "name":"task",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fd9c56bf82ba4434b29ed572914ffb4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":160},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2101e64a5004c87a060d8786d0271cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":160},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/task/u0.png"}},
{
          "id":"e7534b8141e54f478e863e5af933dca6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFCCFF},
            "size":{
              "width":1100,
              "height":790}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4a6cd5ace0247feb3d760af2392c9ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFCCFF},
                "size":{
                  "width":1100,
                  "height":790}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/task/u2.png"}},
{
          "id":"d59d96e334694c0ca4e1d3331d577bef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF57ADD0},
            "location":{
              "x":1001,
              "y":584},
            "size":{
              "width":30,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "linePattern":"solid",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b719ceefd994e8d8fe7bc170f6813ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF57ADD0},
                "location":{
                  "x":1001,
                  "y":584},
                "size":{
                  "width":30,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "linePattern":"solid",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/page_1/u417.png"}},
{
          "id":"0686ab5435ce428d82634ccaffd7eeae",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1006,
              "y":587},
            "size":{
              "width":20,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/page_1/u419_line.png"}},
{
          "id":"3555a374b96146618cadf7035d88588f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1006,
              "y":593},
            "size":{
              "width":20,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/page_1/u419_line.png"}},
{
          "id":"379b7b0253434712bd1550621953ebf9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1006,
              "y":599},
            "size":{
              "width":20,
              "height":10},
            "borderWidth":"3",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/page_1/u419_line.png"}},
{
          "id":"65fa4b938cdb4298a20c07dfd665dd8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Rounded MT Bold', 'Arial Rounded MT'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1007,
              "y":566},
            "size":{
              "width":20,
              "height":20},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e119cbf6f4443c586beacdd2acb077c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Rounded MT Bold', 'Arial Rounded MT'",
                "fontSize":"36px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1007,
                  "y":566},
                "size":{
                  "width":20,
                  "height":20},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42495f69bab842378ab6301e4a861793",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":1001,
              "y":584},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Show taskm",
                      "objectsToFades":[{
                          "objectPath":["d59bf3d93f5f4e0fbd9f08588ce0a4a3"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
          "label":"taskm",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":801,
              "y":470},
            "size":{
              "width":470,
              "height":348},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"a5bd3fcd0bb845ecb9ce3780b9b13a8c",
              "label":"State1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0ac1f4aa236b4760b0afc10300809da3",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":220,
                      "height":220},
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"5",
                    "outerShadow":{
                      "on":true,
                      "offsetX":1,
                      "offsetY":1,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2535ee67ad9b491a825cf4659483ed41",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":220,
                          "height":220},
                        "borderWidth":"1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"5",
                        "outerShadow":{
                          "on":true,
                          "offsetX":1,
                          "offsetY":1,
                          "blurRadius":5,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/task/u13.png"}},
{
                  "id":"12f8f982e3e54fb7a3bdf939aea11539",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F3F6},
                    "location":{
                      "x":12,
                      "y":11},
                    "size":{
                      "width":198,
                      "height":59},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "linePattern":"solid"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c0452240138945bf979e35e3f863b7b1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F3F6},
                        "location":{
                          "x":12,
                          "y":11},
                        "size":{
                          "width":198,
                          "height":59},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "linePattern":"solid"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/task/u15.png"}},
{
                  "id":"912efe20e1ef4cdf8574a042e1b9d385",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF59CE93},
                    "location":{
                      "x":17,
                      "y":16},
                    "size":{
                      "width":45,
                      "height":19},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ad726971fa094f8f8881600361b7d01e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF59CE93},
                        "location":{
                          "x":17,
                          "y":16},
                        "size":{
                          "width":45,
                          "height":19},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Show/Hide Widget",
                              "objectsToFades":[]},
{
                              "action":"setFunction",
                              "description":"Set is selected of Unidentified equal to &quot;toggle&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/task/u17.png"}},
{
                  "id":"69693652af2445ae97bc8de0fe7b16f2",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":67,
                      "y":16},
                    "size":{
                      "width":105,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4a18f322e5944eafa6214c52fc8c30ab",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":67,
                          "y":16},
                        "size":{
                          "width":105,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f0a336028ae14c5485e66434acbf0ef9",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":15,
                      "y":40},
                    "size":{
                      "width":190,
                      "height":21},
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"82a685b7e9724f03b6457681c42bba23",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":15,
                          "y":40},
                        "size":{
                          "width":190,
                          "height":21},
                        "borderWidth":"1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/task/u21.png"}},
{
                  "id":"8dbf4870e5d74fab84c5bdc54e59539f",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF54ADD3},
                    "location":{
                      "x":15,
                      "y":41},
                    "size":{
                      "width":126,
                      "height":19},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3933bf0ffa4a4961883787a1eb0cbe49",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF54ADD3},
                        "location":{
                          "x":15,
                          "y":41},
                        "size":{
                          "width":126,
                          "height":19},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/task/u23.png"}},
{
                  "id":"e94f1909d38b4d9087506aa72892446f",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":104,
                      "y":41},
                    "size":{
                      "width":26,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7b8a7d444d61450daea8338f0ddde627",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":104,
                          "y":41},
                        "size":{
                          "width":26,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"373850c247874dc293f08653d3fa6949",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":70},
                    "size":{
                      "width":198,
                      "height":59},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "linePattern":"solid"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8e2b253c827a4e66bfb037cabfdc7ea6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":70},
                        "size":{
                          "width":198,
                          "height":59},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "linePattern":"solid"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/task/u27.png"}},
{
                  "id":"2e302ea3196c469cb1283e07e3829b37",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF59CE93},
                    "location":{
                      "x":17,
                      "y":75},
                    "size":{
                      "width":45,
                      "height":19},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"571480133d96450dac75e01ddd31dabf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF59CE93},
                        "location":{
                          "x":17,
                          "y":75},
                        "size":{
                          "width":45,
                          "height":19},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Show/Hide Widget",
                              "objectsToFades":[]},
{
                              "action":"setFunction",
                              "description":"Set is selected of Unidentified equal to &quot;toggle&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/task/u17.png"}},
{
                  "id":"08d4b369a1d448c4ab069894cbecbfb1",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":67,
                      "y":75},
                    "size":{
                      "width":105,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8d4d6d89e49f4729a1b5d1d4140950af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":67,
                          "y":75},
                        "size":{
                          "width":105,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"10c3c18a462e402980dc15884f8fb178",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":15,
                      "y":99},
                    "size":{
                      "width":190,
                      "height":21},
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dd4111fc6dce43dfb6c100b76d9966f9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":15,
                          "y":99},
                        "size":{
                          "width":190,
                          "height":21},
                        "borderWidth":"1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/task/u21.png"}},
{
                  "id":"b448629a7a924807bddfab3de6da7de5",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF54ADD3},
                    "location":{
                      "x":15,
                      "y":100},
                    "size":{
                      "width":96,
                      "height":19},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e019a11413bf4459a1cd1caedbad27cb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF54ADD3},
                        "location":{
                          "x":15,
                          "y":100},
                        "size":{
                          "width":96,
                          "height":19},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/task/u35.png"}},
{
                  "id":"21c12b261023439da813bb5d26360e67",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":77,
                      "y":100},
                    "size":{
                      "width":26,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"79ffed0e0876402a8cf433d21ff81ad5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":77,
                          "y":100},
                        "size":{
                          "width":26,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d3bcd1f880e34e2bab2311f7b0bd3d22",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F3F6},
                    "location":{
                      "x":12,
                      "y":129},
                    "size":{
                      "width":198,
                      "height":59},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "linePattern":"solid"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"09ef94cc847f49ca9f968103861fb385",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F3F6},
                        "location":{
                          "x":12,
                          "y":129},
                        "size":{
                          "width":198,
                          "height":59},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "linePattern":"solid"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/task/u15.png"}},
{
                  "id":"bac78dc4be214e6e80f9c141c3172207",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF59CE93},
                    "location":{
                      "x":17,
                      "y":134},
                    "size":{
                      "width":45,
                      "height":19},
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5be467bdc7834d1e82ab2f488c84f93f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF59CE93},
                        "location":{
                          "x":17,
                          "y":134},
                        "size":{
                          "width":45,
                          "height":19},
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Show/Hide Widget",
                              "objectsToFades":[]},
{
                              "action":"setFunction",
                              "description":"Set is selected of Unidentified equal to &quot;toggle&quot;",
                              "expr":{
                                "exprType":"block",
                                "subExprs":[]}}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/task/u17.png"}},
{
                  "id":"1e1dbcc0ea304a95b796d4644caabeb2",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":67,
                      "y":134},
                    "size":{
                      "width":105,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e4e56d68a1b345f385f34b880603aaa6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":67,
                          "y":134},
                        "size":{
                          "width":105,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ee4b31befb7e410b984feb1391f9e47e",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":15,
                      "y":158},
                    "size":{
                      "width":190,
                      "height":21},
                    "borderWidth":"1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5e710c7e3efa440da122b06dc0473daf",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":15,
                          "y":158},
                        "size":{
                          "width":190,
                          "height":21},
                        "borderWidth":"1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/task/u21.png"}},
{
                  "id":"865b6e954b8a4089b23830e4b1619ab0",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF54ADD3},
                    "location":{
                      "x":15,
                      "y":159},
                    "size":{
                      "width":47,
                      "height":19},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "linePattern":"solid",
                    "cornerRadiusTopLeft":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a21fa3c992a6409e943cd81e023130d1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF54ADD3},
                        "location":{
                          "x":15,
                          "y":159},
                        "size":{
                          "width":47,
                          "height":19},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "linePattern":"solid",
                        "cornerRadiusTopLeft":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/task/u47.png"}},
{
                  "id":"c17049c7190d4b9aa5d0f42d07b3c3f6",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":27,
                      "y":159},
                    "size":{
                      "width":26,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"58419be210dd4c48a5d2272e7ea29419",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":27,
                          "y":159},
                        "size":{
                          "width":26,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4bf222dc5ace4dd19ec64d5b856e760e",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "underline":true,
                    "location":{
                      "x":154,
                      "y":189},
                    "size":{
                      "width":25,
                      "height":17}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1016d9ec51f548b5a0274676809fe4fd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "underline":true,
                        "location":{
                          "x":154,
                          "y":189},
                        "size":{
                          "width":25,
                          "height":17}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0cd8494a174847bcab9ba435388ee98d",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":190,
                      "y":16},
                    "size":{
                      "width":15,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b44886eb8567480a8db9b9a3f9d35b01",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":190,
                          "y":16},
                        "size":{
                          "width":15,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_1/u62.png"}},
{
                  "id":"51047b69687449c0810d402ee44799e7",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":190,
                      "y":76},
                    "size":{
                      "width":15,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e922fb372a9f4e72b90d0d023b152849",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":190,
                          "y":76},
                        "size":{
                          "width":15,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_1/u62.png"}},
{
                  "id":"a67cf0f531644ba785fb328ab492228c",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":190,
                      "y":133},
                    "size":{
                      "width":15,
                      "height":15}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b069e109a4eb4a678322e98023f3309c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":190,
                          "y":133},
                        "size":{
                          "width":15,
                          "height":15}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/page_1/u62.png"}},
{
                  "id":"3dcb1e3cd1934dfab9aca31e4b097a38",
                  "label":"",
                  "parentDynamicPanel":"d59bf3d93f5f4e0fbd9f08588ce0a4a3",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":220,
                      "height":220}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"Case 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"Hide taskm",
                              "objectsToFades":[{
                                  "objectPath":["d59bf3d93f5f4e0fbd9f08588ce0a4a3"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "fd9c56bf82ba4434b29ed572914ffb4a":{
      "scriptId":"u0"},
    "d2101e64a5004c87a060d8786d0271cb":{
      "scriptId":"u1"},
    "e7534b8141e54f478e863e5af933dca6":{
      "scriptId":"u2"},
    "e4a6cd5ace0247feb3d760af2392c9ac":{
      "scriptId":"u3"},
    "d59d96e334694c0ca4e1d3331d577bef":{
      "scriptId":"u4"},
    "5b719ceefd994e8d8fe7bc170f6813ab":{
      "scriptId":"u5"},
    "0686ab5435ce428d82634ccaffd7eeae":{
      "scriptId":"u6"},
    "3555a374b96146618cadf7035d88588f":{
      "scriptId":"u7"},
    "379b7b0253434712bd1550621953ebf9":{
      "scriptId":"u8"},
    "65fa4b938cdb4298a20c07dfd665dd8d":{
      "scriptId":"u9"},
    "2e119cbf6f4443c586beacdd2acb077c":{
      "scriptId":"u10"},
    "42495f69bab842378ab6301e4a861793":{
      "scriptId":"u11"},
    "d59bf3d93f5f4e0fbd9f08588ce0a4a3":{
      "scriptId":"u12"},
    "0ac1f4aa236b4760b0afc10300809da3":{
      "scriptId":"u13"},
    "2535ee67ad9b491a825cf4659483ed41":{
      "scriptId":"u14"},
    "12f8f982e3e54fb7a3bdf939aea11539":{
      "scriptId":"u15"},
    "c0452240138945bf979e35e3f863b7b1":{
      "scriptId":"u16"},
    "912efe20e1ef4cdf8574a042e1b9d385":{
      "scriptId":"u17"},
    "ad726971fa094f8f8881600361b7d01e":{
      "scriptId":"u18"},
    "69693652af2445ae97bc8de0fe7b16f2":{
      "scriptId":"u19"},
    "4a18f322e5944eafa6214c52fc8c30ab":{
      "scriptId":"u20"},
    "f0a336028ae14c5485e66434acbf0ef9":{
      "scriptId":"u21"},
    "82a685b7e9724f03b6457681c42bba23":{
      "scriptId":"u22"},
    "8dbf4870e5d74fab84c5bdc54e59539f":{
      "scriptId":"u23"},
    "3933bf0ffa4a4961883787a1eb0cbe49":{
      "scriptId":"u24"},
    "e94f1909d38b4d9087506aa72892446f":{
      "scriptId":"u25"},
    "7b8a7d444d61450daea8338f0ddde627":{
      "scriptId":"u26"},
    "373850c247874dc293f08653d3fa6949":{
      "scriptId":"u27"},
    "8e2b253c827a4e66bfb037cabfdc7ea6":{
      "scriptId":"u28"},
    "2e302ea3196c469cb1283e07e3829b37":{
      "scriptId":"u29"},
    "571480133d96450dac75e01ddd31dabf":{
      "scriptId":"u30"},
    "08d4b369a1d448c4ab069894cbecbfb1":{
      "scriptId":"u31"},
    "8d4d6d89e49f4729a1b5d1d4140950af":{
      "scriptId":"u32"},
    "10c3c18a462e402980dc15884f8fb178":{
      "scriptId":"u33"},
    "dd4111fc6dce43dfb6c100b76d9966f9":{
      "scriptId":"u34"},
    "b448629a7a924807bddfab3de6da7de5":{
      "scriptId":"u35"},
    "e019a11413bf4459a1cd1caedbad27cb":{
      "scriptId":"u36"},
    "21c12b261023439da813bb5d26360e67":{
      "scriptId":"u37"},
    "79ffed0e0876402a8cf433d21ff81ad5":{
      "scriptId":"u38"},
    "d3bcd1f880e34e2bab2311f7b0bd3d22":{
      "scriptId":"u39"},
    "09ef94cc847f49ca9f968103861fb385":{
      "scriptId":"u40"},
    "bac78dc4be214e6e80f9c141c3172207":{
      "scriptId":"u41"},
    "5be467bdc7834d1e82ab2f488c84f93f":{
      "scriptId":"u42"},
    "1e1dbcc0ea304a95b796d4644caabeb2":{
      "scriptId":"u43"},
    "e4e56d68a1b345f385f34b880603aaa6":{
      "scriptId":"u44"},
    "ee4b31befb7e410b984feb1391f9e47e":{
      "scriptId":"u45"},
    "5e710c7e3efa440da122b06dc0473daf":{
      "scriptId":"u46"},
    "865b6e954b8a4089b23830e4b1619ab0":{
      "scriptId":"u47"},
    "a21fa3c992a6409e943cd81e023130d1":{
      "scriptId":"u48"},
    "c17049c7190d4b9aa5d0f42d07b3c3f6":{
      "scriptId":"u49"},
    "58419be210dd4c48a5d2272e7ea29419":{
      "scriptId":"u50"},
    "4bf222dc5ace4dd19ec64d5b856e760e":{
      "scriptId":"u51"},
    "1016d9ec51f548b5a0274676809fe4fd":{
      "scriptId":"u52"},
    "0cd8494a174847bcab9ba435388ee98d":{
      "scriptId":"u53"},
    "b44886eb8567480a8db9b9a3f9d35b01":{
      "scriptId":"u54"},
    "51047b69687449c0810d402ee44799e7":{
      "scriptId":"u55"},
    "e922fb372a9f4e72b90d0d023b152849":{
      "scriptId":"u56"},
    "a67cf0f531644ba785fb328ab492228c":{
      "scriptId":"u57"},
    "b069e109a4eb4a678322e98023f3309c":{
      "scriptId":"u58"},
    "3dcb1e3cd1934dfab9aca31e4b097a38":{
      "scriptId":"u59"}}});